car:
  image: sanderkleykens/car:5.10.6
  restart: always
  environment:
    - CATALINA_OPTS=-Xms${heap_size} -Xmx${heap_size} ${jvm_args}
    - car_PROXY_PORT=${proxy_port}
    - car_PROXY_NAME=${proxy_name}
    - car_PROXY_SCHEME=${proxy_scheme}
    - car_CONTEXT_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${car_home}:/var/atlassian/car
