.catalog:
  name: OA应用
  version: v1.0
  description: |
    (tomcat)OA应用
  minimum_rancher_version: v0.5.0
tomcat-oa:
  scale: 1
  health_check:
    port: 8081
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
