.catalog:
  name: "bmxdsitedb"
  version: "v0.0.1"
  description: "A recommended stack for the MySQL RDBMS."
  minimum_rancher_version: v1.0.0
mysql:
  scale: 1
  image: 192.168.1.15:5000/smsdb:v5
  health_check:
    port: 3306
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
