.catalog:
  name: "mysql"
  version: "v0.0.1"
  description: "A recommended stack for the MySQL RDBMS."
version: '1'
mysql:
	scale: 1
	start_on_create: true
	health_check:
	  healthy_threshold: 2
	  response_timeout: 2000
	  port: 3306
	  unhealthy_threshold: 3
	  interval: 2000
	  strategy: recreate

